### ISSUE TITLE
Issue regarding spaces in Twitter

### ISSUE THREAD

**Issue by Jassi10000-zz** [twitter-space-station/frontend#29]
Is this is the repo for Twitter spaces ? , I want to express an issue

**Comment by SnO2WMaN** [comment]
Yes but I was tired of this, I won't develop no longer. What's matter?

**Comment by Jassi10000-zz** [comment]
Ooo , I don't think you should stop , its really a gr8 addition to the App 🤩
But the only issue am facing , after joining a Space , my phone gets soooooooo heated up 🥵🥵 , that I have to close the App immediately .
It would be nice if you start working again , I can also help you in the process , maybe I can learn something and maybe also give some best ideas 
But my only suggestion would be continue this without getting tired

**Comment by SnO2WMaN** [comment]
I think you just misunderstanding something, it's just a hobby service, not official something for twitter space.

I'm closing this.

**Comment by Jassi10000-zz** [comment]
> I think you just misunderstanding something, it's just a hobby service, not official something for twitter space.
> 
> I'm closing this.

Is that not for spaces that's used for official Twitter ?
